### ISSUE TITLE
 Failed to authenticate using the given account Credentials

### ISSUE THREAD

**Issue by Char0nDev** [Rishikant181/Rettiwt-API#578] opened 2024-08-03 14:25 UTC
i enter the right credentials but the display the error ( Failed to authenticate using the given account Credentials)

**Comment by Rishikant181** [comment] 2024-08-03 14:28
Do you have 2FA enabled?

**Comment by Char0nDev** [comment] 2024-08-03 14:29
> Do you have 2FA enabled?

no

**Comment by Char0nDev** [comment] 2024-08-03 14:37
@Rishikant181

**Comment by Rishikant181** [comment] 2024-08-03 14:45
Did you try enclosing you credentials in double quotes like this?: `rettiwt auth login "email" "username" "password"`

**Comment by Char0nDev** [comment] 2024-08-03 14:52
> Did you try enclosing you credentials in double quotes like this?: `rettiwt auth login "email" "username" "password"`

i do it with "" and without "" but the same result

**Comment by Rishikant181** [comment] 2024-08-03 14:53
Try it and see if it works

**Comment by Char0nDev** [comment] 2024-08-03 14:53
i do it with "" and without "" but the same result

**Comment by Char0nDev** [comment] 2024-08-03 14:55
![image](https://github.com/user-attachments/assets/f10e06bc-1c4f-4a13-b2ec-f8a434b4ffb3)

**Comment by Char0nDev** [comment] 2024-08-03 14:56
@Rishikant181 it is diplay it

**Comment by Rishikant181** [comment] 2024-08-03 14:58
Try logging in to Twitter from a browser using the same account, then try rettiwt auth again.

**Comment by Char0nDev** [comment] 2024-08-03 15:03
> Try logging in to Twitter from a browser using the same account, then try rettiwt auth again.

i already try that

**Comment by Char0nDev** [comment] 2024-08-03 15:03
the credentials are 100% right

**Comment by Char0nDev** [comment] 2024-08-03 15:09
@Rishikant181

**Comment by Rishikant181** [comment] 2024-08-03 15:30
Okay I have a temporary workaround:

1. Open your browser and go to twitter/X.
2. Open browser developer tools.
3. Navigate to Applications->Cookies (for Chrome) or Storage->Cookies (for Firefox).
4. Copy the values of the 4 fields: `auth_token`, `ct0`, `kdt`, `twid`. Store them temporarily somewhere.
5. Open NodeJS in a terminal and execute the command: `btoa("auth_token=<auth_token_value>;ct0=<ct0_value>;kdt=<kdt_value>;twid=<twid_value>")`
6. The output  string is your API_KEY.

I'll be trying to reproduce the error. So far, I couldn't (it's working as expected for me).

On a side note, this has been a long standing issue, which I have not been able to reproduce myself. For some people, it throws the error, while it works after some time. This workaround help you continue your work (hopefullt).

I'll be keeping this issue pinned.

**Comment by Rishikant181** [comment] 2024-08-03 15:35
Duplicate of #493

**Comment by Rishikant181** [comment] 2024-08-03 15:35
@Char0nDev All updates regarding this issue will be tracked at #493

**Comment by Rishikant181** [comment] 2024-08-03 15:37
@Char0nDev The earlier posted code was incorrect, please check again.

**Closed as completed** 2024-08-03 15:43 UTC
