### ISSUE TITLE
Failed to authenticate using the given account Credentials

### ISSUE THREAD

**Issue by Othmanosx** [Rishikant181/Rettiwt-API#493] opened 2024-03-13 00:02 UTC
facing this issue when creating an api key.
I had a working API key before but it suddenly stopped working, when I checked the account it was suspended so I created a new fresh account but I still got the same issue, the account itself still works on twitter with no errors, but I can't generate an API key with it.
I used www.moakt.com to get the disposable email I used to create the account.
```
othman@othmans-13-mbp ~ % rettiwt auth login my-burner-email account-id password
/usr/local/lib/node_modules/rettiwt-api/node_modules/rettiwt-auth/dist/Auth.js:235
                                                throw new Error(_this.parseAuthError(err, _this.subtasks[i]));
                                                      ^

Error: Failed to authenticate using the given account Credentials
    at /usr/local/lib/node_modules/rettiwt-api/node_modules/rettiwt-auth/dist/Auth.js:235:55
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

Node.js v21.6.1
```

**Comment by Othmanosx** [comment] 2024-03-13 00:27
Update: I created my own API key by encoding the cookie I copied from twitter request headers, plugged it in and it's working.
`rettiwt auth login my-burner-email account-id password` still doesn't work.

**Comment by Rishikant181** [comment] 2024-03-13 04:58
This issue has been bugging me for a lot of time and I am never able to find the cause since I am yet to face the issue myself. I even created many fresh burner account but all the time it just works.

I am actively investigating it though.

**Comment by Othmanosx** [comment] 2024-03-13 05:01
Thanks!
Do let me know if you need any help, you've done an awesome job on this package!

**Comment by AlejandroAkbal** [comment] 2024-03-13 09:55
For me, it was because the password had unique characters like $%^

**Comment by Rishikant181** [comment] 2024-03-13 14:21
@AlejandroAkbal Any idea about [this](https://github.com/Rishikant181/Rettiwt-API/issues/479)?

**Comment by AlejandroAkbal** [comment] 2024-03-13 14:54
Don't know about that, I got it working by logging with code, so the password string gets send successfully

Unlike with the CLI

**Comment by Othmanosx** [comment] 2024-03-13 15:20
Update: my token expired overnight :( 
also, I don't have unique characters in my password.

**Comment by Rishikant181** [comment] 2024-03-14 05:52
@Othmanosx And the twitter account still works?

**Comment by Othmanosx** [comment] 2024-03-14 22:51
Yup, still works

**Comment by Othmanosx** [comment] 2024-03-14 23:02
Update: just tried again now, and it's working, I can generate a new API key with the CLI.
I didn't change anything!

**Comment by Rishikant181** [comment] 2024-03-15 16:49
@Othmanosx That's why it's not been fixed yet. The issue can't be reproduced easily:(

**Comment by Othmanosx** [comment] 2024-03-15 23:54
Absolutely.

**Comment by Othmanosx** [comment] 2024-04-06 17:54
@Rishikant181 have we found a fix for the expiring keys?
API keys generated by the CLI don't last more than a day :\
I've used multiple accounts with temporary and Gmail emails, while the temporary ones get locked quickly, the account opened with Gmail didn't get locked, but the key expires overnight regardless.

**Comment by Rishikant181** [comment] 2024-04-06 19:00
I'm yet to reproduce the issue. I even created numerous burner accounts just for them to work flawlessly :(

One thing you can try is maybe dial down the rate of sending requests to see if it mitigates the issue?

**Comment by Othmanosx** [comment] 2024-04-08 16:22
I dialed down the rate greatly, still expired after one day :(

**Comment by Nevgup** [comment] 2024-04-09 08:27
yes, same for me

**Comment by Nevgup** [comment] 2024-04-09 08:34
Hello
I think I have the same problem, it expires after 1 day

For example, with accounts that I generated their apiKeys 1-2 days ago : I can try to get details of an user an it will output this :

```
RettiwtError: Failed to authenticate
    at ApiError.RettiwtError [as constructor]
    at new ApiError
    at exports.ErrorService.ErrorService.createApiError:124:16)
    at exports.ErrorService.ErrorService.handleApiError:85:20)
    at exports.ErrorService.ErrorService.handle
    at rettiwt-api\dist\services\internal\FetcherService.js:187:52
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  code: 32
}
```

But if I regen the apiKey, it will works

**Comment by Rishikant181** [comment] 2024-04-10 04:27
If that's the case, regenerating API KEYs every day will not be an issue, however, I'm still not able to figure what triggers the invalidation :(

This issue will take time to get fixed since I'm working on my final year Major Project, which is due in the first week of May, and have been quite busy lately. Your patience will be invaluable.

**Comment by Nevgup** [comment] 2024-04-11 21:56
Indeed regenerating is not a problem, but now I have a lot of accounts with this error :
```
Error: Failed to authenticate using the given account Credentials
```
So thats weird, if I have more informations i'll get back


(ofc np, take your time)

**Comment by Nevgup** [comment] 2024-04-11 21:57
Indeed regenerating is not a problem, but now I have a lot of accounts with this error : (because I wanted to regenerate it)
```
Error: Failed to authenticate using the given account Credentials
```
So thats weird, if I have more informations i'll get back
Maybe i'm wrong for the 1day api key

(ofc np, take your time)

**Comment by Rishikant181** [comment] 2024-08-03 15:33
[Workaround](https://github.com/Rishikant181/Rettiwt-API/issues/578#issuecomment-2266813924)

**Comment by Rishikant181** [comment] 2024-08-03 15:34
Okay I have a temporary workaround:

1. Open your browser and go to twitter/X.
2. Open browser developer tools.
3. Navigate to Applications->Cookies (for Chrome) or Storage->Cookies (for Firefox).
4. Copy the values of the 4 fields: `auth_token`, `ct0`, `kdt`, `twid`. Store them temporarily somewhere.
5. Open NodeJS in a terminal and execute the command: `btoa("auth_token=<auth_token_value>;ct0=<ct0_value>;kdt=<kdt_value>;twid=<twid_value>")`
6. The output  string is your API_KEY.

**Comment by Char0nDev** [comment] 2024-08-03 15:42
> Okay I have a temporary workaround:
> 
> 1. Open your browser and go to twitter/X.
> 2. Open browser developer tools.
> 3. Navigate to Applications->Cookies (for Chrome) or Storage->Cookies (for Firefox).
> 4. Copy the values of the 4 fields: `auth_token`, `ct0`, `kdt`, `twid`. Store them temporarily somewhere.
> 5. Open NodeJS in a terminal and execute the command: `btoa("auth_token=<auth_token_value>;ct0=<ct0_value>;kdt=<kdt_value>;twid=<twid_value>")`
> 6. The output  string is your API_KEY.

now it is work good , Thank you for help 🙏

**Comment by Rishikant181** [comment] 2024-08-08 11:04
Further discussion and updates will be posted at #586 .

**Comment by Rishikant181** [comment] 2024-08-08 11:05
Duplicate of #586

**Closed as completed by Rishikant181** 2024-08-08 11:05 UTC
