### ISSUE TITLE
Error trying to get an API Key (Again)

### ISSUE THREAD

**Issue by MDCYT** [Rishikant181/Rettiwt-API#479] opened 2024-02-28 20:24 UTC
Hello, this error had already happened to me (#453), but this time I was able to make a console.log()

![image](https://t.mdcdev.me/qe3vi1h8)

**Comment by Rishikant181** [comment] 2024-02-29 05:10
And logging in with the same account on a browser works, i presume?

**Comment by MDCYT** [comment] 2024-02-29 05:41
Yeah

**Comment by Rishikant181** [comment] 2024-02-29 05:46
This issue is starting to give me a lot of headache. I'm gonna need some details.

1. Is this a burner account that you created just for scraping?
2. How old is the account?
3. When logging into Twitter web app using this account, did you ever need some form of verification out of the blue?
4. How many other devices is this account logged into?
5. Did you try using your primary Twitter account (which you use normally for browsing Twitter)?

**Comment by MDCYT** [comment] 2024-02-29 05:50
> 1. Is this a burner account that you created just for scraping?

In this case yes, but in the previous case that didn't work either try with 2022 and 2019 accounts.

> 2. How old is the account?

In this case it was created yesterday.

> 3. When logging into Twitter web app using this account, did you ever need some form of verification out of the blue?

Nop

> 4. How many other devices is this account logged into?

Only my web browser where I created the account

> 5. Did you try using your primary Twitter account (which you use normally for browsing Twitter)?

Yes, in the first Isue apart from the accounts I said I also tried with my personal 2018 account.

**Comment by MDCYT** [comment] 2024-02-29 05:57
If you wish, I can send you the complete log so that you can see which could be the errors.

**Comment by Rishikant181** [comment] 2024-02-29 06:04
@MDCYT No need, the error code 400 sent by Twitter is actually a misleading status, and it just stands for "Lol, we detected you're not a human, so no login for you". Atleast that's what I have observed.

One thing to add though, I have been testing this package with my primary Twitter account since the day the package was created, and never once did I encounter this issue. That's the trouble I'm facing. Guess I'll have to create a burner account to reproduce this issue.

I have an alternate solution: Using puppeteer just for authentication.

**Comment by MDCYT** [comment] 2024-02-29 06:06
You could fix it, or you could do that by copying and pasting the browser cookies the program makes a token too, that's what I did after for some reason one of the tokens I was testing got invalidated at night.

**Comment by Rishikant181** [comment] 2024-02-29 06:09
Yes, copying the cookies from the browser devtools and encoding them as base64 will do the job.

**Comment by Rishikant181** [comment] 2024-02-29 06:51
@MDCYT I too tried with a fresh burner account and it works :(

I still can't reproduce the issue :(

Edit 1: From now on, I'll be using the newly created burner account for all scraping and testing purposes, in hopes of reproducing the issue.

**Comment by MDCYT** [comment] 2024-02-29 14:42
I don't think it's not only a problem with new accounts, because the other time I tried it, it didn't let me create a token with any account, even if it was old or my main one wouldn't let me. The next day when I tried if I let me with all accounts.

**Comment by MDCYT** [comment] 2024-02-29 14:54
Maybe this error is also due to the fact that when you try to log in you are trying to log in from an unrecognized device?

![image](https://t.mdcdev.me/9736bkuj)

**Comment by Rishikant181** [comment] 2024-08-08 11:02
Further discussions related to this issue will be discussed at #586

**Comment by Rishikant181** [comment] 2024-08-08 11:05
Duplicate of #586

**Closed as completed by Rishikant181** 2024-08-08 11:05 UTC
