### ISSUE TITLE
Login with Proxy not working

### ISSUE THREAD

**Issue by DavideMacchia** [Rishikant181/Rettiwt-API#585] opened 2024-08-08 08:31 UTC
It's from the 4th/5th of august that if we try to login from CLI or code using a proxy the result is an empty object or the message "**Failed to authenticate using the given account Credentials**".
We have tried using different proxies (bought from different sources) and the account has no problems to login correctly from browser (using the same proxies).
If we try to login without proxy the api key is returned correctly, both from CLI and code.
We created a brand new account, but it's not working at all, either using the proxy or not.

What could be the problem?

**Comment by Rishikant181** [comment] 2024-08-08 10:14
What type of user input is required while logging in from the browser? I mean, does logging in from browser require just the email, username and password, or something else?

**Comment by DavideMacchia** [comment] 2024-08-08 10:37
It require only email and password, nothing else is required.

**Comment by Rishikant181** [comment] 2024-08-08 10:58
Further discussion and updates will be posted at #586

**Comment by Rishikant181** [comment] 2024-08-08 11:05
Duplicate of #586

**Closed as completed by Rishikant181** 2024-08-08 11:05 UTC
