### ISSUE TITLE
Error trying to get an API Key

### ISSUE THREAD

**Issue by MDCYT** [Rishikant181/Rettiwt-API#453] opened 2024-02-09 19:10 UTC
I have been trying to get an api key with 2 accounts I had, and even with a newly created account, but I always get the same error.

![image](https://github.com/Rishikant181/Rettiwt-API/assets/67084442/a46fe54e-1593-4284-8b46-1ee441f627b1)

Version: 2.5.1

**Comment by Rishikant181** [comment] 2024-02-09 19:45
Are those two accounts accessible right now from the Twitter Web App?

**Comment by MDCYT** [comment] 2024-02-09 20:48
yes, the 3 accounts I tried I tried with the session logged into twitter.com, I also tried logging out, trying again and then logging back in and trying again.

**Comment by Rishikant181** [comment] 2024-02-10 03:58
Guess we'll have to manually check what error message is being throw by Twitter API. The error as seen above is a generic error message, which is thrown by default whenever an error occurs.

Please try logging the actual error message from Twitter by logging the error on line 235 of the file \node_modules\rettiwt-auth\dist\Auth.js, as follows:

![image](https://github.com/Rishikant181/Rettiwt-API/assets/66668688/af507e5f-4108-43a6-a8a7-8ed69e6e7881)

**Comment by MDCYT** [comment] 2024-02-10 17:18
I was putting the console.log() to test, and I have not changed anything since yesterday, I used the same data from an account I tried yesterday and now it returned the token, I do not understand what changed between yesterday and today but for some reason it worked lol.

![image](https://github.com/Rishikant181/Rettiwt-API/assets/67084442/70d7dc33-f8a3-441c-a1fe-9d63d1e291c2)

**Comment by Rishikant181** [comment] 2024-02-10 19:06
Yes, there exists this issue where sometimes it doesn't work. I am yet to find a fix for this and the problem is that the issue is not reproducible. Now that you have the API_KEY though, save it and can use it for a year.

**Closed as completed by Rishikant181** 2024-02-10 19:06 UTC
