### ISSUE TITLE
Bulk Scheduling tweets

### ISSUE THREAD

**Issue by ghost** [Rishikant181/Rettiwt-API#577] opened 2024-08-02 00:19 UTC
I would like to inquire about the possibility of scheduling tweets. If this feature is currently unavailable, I would like to request its implementation.

**Comment by Rishikant181** [comment] 2024-08-02 05:28
It has already been requested at #570  and all updates regarding the feature will be tracked there. I'll mark this issue as a duplicate close this one.

**Comment by Rishikant181** [comment] 2024-08-02 05:28
Duplicate of #570

**Closed as completed by Rishikant181** 2024-08-02 05:28 UTC

**Comment by ghost** [comment] 2024-08-03 07:40
Does this have any limitations, like the number of posts per day?

**Comment by Rishikant181** [comment] 2024-08-03 07:57
It carries the same rate limits as the Twitter Web App, which I have not tested myself. But, you will face limits if you make too many requests in a minute (no exact figure available). But for use in short bursts, it's alright.

**Comment by ghost** [comment] 2024-08-03 11:28
Well, I'm going to post 1,500 posts daily. I hope it's under the limit. 🫠
