### ISSUE TITLE
Rettiwt auth login only returning empty object.

### ISSUE THREAD

**Issue by xonack** [Rishikant181/Rettiwt-API#582] opened 2024-08-07 09:08 UTC
When running `rettiwt auth login "<email>" "<username>" "<password>"` I'm just getting an empty object back `{}`. 

It used to work with the same credentials. I've tried for 3 accounts. 

Anyone else experiencing this?

I used [this](https://github.com/Rishikant181/Rettiwt-API/issues/493#issuecomment-2266823842) as a workaround in the meantime.

**Comment by Rishikant181** [comment] 2024-08-07 10:52
This issue has been in effect for quite some time. Unfortunately, now matter how much I try, I have never been able to reproduce this issue. I have some questions though:

1. Are you using a new burner Twitter account, or your permanent, active  Twitter account?
2. Is 2FA set-up on your account?
3. Do you receive some kind of mail to confirm that it was really you trying to login to Twitter?
4. Do you use some kind of VPN or DNS, perhaps?
5. Does the issue show up when you run the `auth` command from your PC, or does it show when the command is run from a cloud environment?
6. Is there something special about you account? Maybe you have premium or something like that?
7. What exactly is the login process when you login to Twitter using the same account on a browser?

**Comment by xonack** [comment] 2024-08-07 14:15
1. I am using 3 accounts. One permanent active, one permanent inactive, and one fully burner.
2. No.
3. Yes I receive emails with a code requiring me to enter it for login.
4. No.
5. On PC I get an empty object `{}`. On cloud I get `Error: Failed to authenticate using the given account Credentials`.
6. I have premium on some of the accounts. Not on the burner one though.
7. I usually just use google login to log into X on a browser. When I use the password method it asks me for my phone number as verification.

**Comment by Rishikant181** [comment] 2024-08-07 16:28
> Yes I receive emails with a code requiring me to enter it for login

This might be the crux of the issue, since handling of one-time codes have not been implemented. The library mimics the process of logging in using just 3 inputs from user: primary user identifier, alternate user identifier (this is usually the username or phone, although I haven't tested the phone identifier) and password.

> I usually just use google login to log into X on a browser. When I use the password method it asks me for my phone number as verification.

So, if I understand correctly, on the browser, the login process for you is:
1. Enter email and password
2. Enter phone number for verification

If so, then try logging in to Rettiwt-API using the following command: `rettiwt auth login "\<email\>" "\<phone\>" "\<password\>"

**Comment by xonack** [comment] 2024-08-08 07:01
> If so, then try logging in to Rettiwt-API using the following command: `rettiwt auth login "" "" ""

sorry, with empty strings?

does the first login request maybe return a link or reference for the athentication challenge to be passed?

**Comment by Rishikant181** [comment] 2024-08-08 07:49
Sorry, I forgot the escape sequence to write "<>". I have edited the comment, do check it again.

**Comment by Rishikant181** [comment] 2024-08-08 10:59
Further discussion and updates will be posted at #586 .

**Comment by Rishikant181** [comment] 2024-08-08 11:05
Duplicate of #586

**Closed as completed by Rishikant181** 2024-08-08 11:05 UTC

**Comment by xonack** [comment] 2024-08-08 11:08
FYI - `rettiwt auth login "<email>" "<phone>" "<password>"` did not work. 

`rettiwt auth login "<phone>" "<email>" "<password>"` didn't either.

**Comment by Rishikant181** [comment] 2024-08-08 11:15
Please continue discussions related to login at #586 . It allows for better gathering of information at one place. I you refer to this [comment](https://github.com/Rishikant181/Rettiwt-API/issues/586#issuecomment-2275560487) for some potential situations where this behavior might be triggered.
